name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build --configuration release
    - name: Create zip file
      run: cd .build/release/ && zip autokbisw-${{github.ref_name}}.zip autokbisw
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .build/release/autokbisw-${{github.ref_name}}.zip
        asset_name: autokbisw-${{github.ref_name}}.zip
        tag: ${{ github.ref }}
        overwrite: true
