name: Tests

on: pull_request

jobs:
  build:
    name: Test build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-11
            os_name: big_sur
          - os: macos-12
            os_name: monterey
          - os: macos-13
            os_name: ventura

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: swift build --configuration release --arch arm64 --arch x86_64
